from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from app.routers import health, todos

app = FastAPI(
    title="[[.ProjectName]] API",
    description="FastAPI Backend generated by Koko-cli",
    version="0.1.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(health.router, prefix="/api", tags=["health"])
app.include_router(todos.router, prefix="/api", tags=["todos"])

if __name__ == "__main__":
    import uvicorn
    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)
