import { generateOpenAPI } from '@orpc/openapi';
import { router } from './root';

export function getOpenAPISpec() {
  return generateOpenAPI({
    router,
    info: {
      title: 'Koko Monorepo API',
      version: '1.0.0',
      description: 'Type-safe OpenAPI generated by oRPC',
    },
  });
}
